---

- name: Make sure UFW is present
  ansible.builtin.package:
    name: ufw
    state: present

- name: Copy default ufw config file to /etc/default/ufw
  ansible.builtin.template:
    src: templates/etc/default/ufw
    dest: /etc/default/ufw
    mode: '0644'
    owner: root
    group: root

- name: Make sure UFW is enabled and started
  ansible.builtin.systemd:
    name: ufw.service
    state: started
    enabled: true
    masked: false

...
